### ISSUE TITLE
improvement: automate command

### ISSUE THREAD

**Issue by termitavee** [zmnv/react-native-semver-update#1]
I don't know if you would like to improve your tool but it would be a great feature (and for me the perfect app) if you could pass a parameter and update all parameters automatically

for example:  rnsemup -version 1.0.1 would do:
set  version 1.0.1 for all platform
increment android build by 1
set ios build to 0 (or 1) if version increased, or increase if same version.

Right now I use React-native-version but it increases forever and don't support increment only build version

**Comment by zmnv** [comment]
### Auto Increase by cli

Build Number:
```
rnsemup -b
```

Project Version:
```
rnsemup -u <unit>
```
where `unit` is:
 * `major` 1.2.3 → 2.0.0  
 * `minor` 1.2.3 → 1.3.0  
 * `patch` 1.2.3 → 1.2.4  

### Example

```
rnsemup -b -u minor
```

1. Increase build number
2. Increase minor in project version
3. Set patch is 0
