### ISSUE TITLE
 TypeError: Cannot read property '2' of null

### ISSUE THREAD

**Issue by Chasty** [zmnv/react-native-semver-update#12]
I'm having this issue when I try to run this command

`rnsemup`

**Comment by zmnv** [comment]
@Chasty Hello! Maybe I found the same bug as you get. 

Can you check the project versions in iOS and Android?
Please change version format :
```1.0 -> 1.0.0```

and try again.

**Comment by zmnv** [comment]
Reproduced this bug!

1. `npx react-native init AwesomeProject`
2. `cd AwesomeProject`
3. `rnsemup`

gets:
```
(node:7920) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '2' of null
```

**Comment by Chasty** [comment]
@zmnv Thank you for your fast response, it was that, the command is running correct now.

**Comment by denverxd** [comment]
Hi, Sorry for asking but I'm not sure where will I change in IOS?
